/** @type {import('tailwindcss').Config} */
export default {
    darkMode: ["class"],
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
            },
            colors: {
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                primary: {
                    DEFAULT: "hsl(var(--primary))",
                    foreground: "hsl(var(--primary-foreground))",
                    container: "hsl(var(--primary-container))",
                    dim: "hsl(var(--primary-dim))",
                    fixed: "hsl(var(--primary-fixed))",
                    fixedDim: "hsl(var(--primary-fixed-dim))",
                },
                secondary: {
                    DEFAULT: "hsl(var(--secondary))",
                    foreground: "hsl(var(--secondary-foreground))",
                    container: "hsl(var(--secondary-container))",
                    dim: "hsl(var(--secondary-dim))",
                    fixed: "hsl(var(--secondary-fixed))",
                    fixedDim: "hsl(var(--secondary-fixed-dim))",
                },
                tertiary: {
                    DEFAULT: "hsl(var(--tertiary))",
                    foreground: "hsl(var(--tertiary-foreground))",
                    container: "hsl(var(--tertiary-container))",
                    dim: "hsl(var(--tertiary-dim))",
                    fixed: "hsl(var(--tertiary-fixed))",
                    fixedDim: "hsl(var(--tertiary-fixed-dim))",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                    container: "hsl(var(--error-container))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
                success: {
                    DEFAULT: "#22c55e",
                    foreground: "#ffffff",
                },
                warning: {
                    DEFAULT: "#eab308",
                    foreground: "#000000",
                },
                // Colores del mockup
                "on-background": "#2d3335",
                "on-secondary": "#f5f9ff",
                "surface-container-high": "#e5e9eb",
                "surface-container-highest": "#dee3e6",
                "on-secondary-container": "#3a5569",
                "inverse-surface": "#0c0f10",
                "outline": "#767c7e",
                "on-tertiary-container": "#495867",
                "on-primary": "#e7fef3",
                "on-error": "#fff7f6",
                "surface": "#f8f9fa",
                "on-primary-fixed": "#2f433c",
                "on-surface-variant": "#5a6062",
                "on-secondary-fixed-variant": "#445e73",
                "on-surface": "#2d3335",
                "surface-dim": "#d5dbdd",
                "surface-container-low": "#f1f4f5",
                "surface-variant": "#dee3e6",
                "on-primary-container": "#42564e",
                "surface-container-lowest": "#ffffff",
                "on-secondary-fixed": "#274255",
                "on-tertiary": "#f6f9ff",
                "error": "#a83836",
                "surface-bright": "#f8f9fa",
                "inverse-on-surface": "#9b9d9e",
                "error-dim": "#67040d",
                "outline-variant": "#adb3b5",
                "inverse-primary": "#e7fff3",
                "surface-container": "#ebeef0",
                "on-error-container": "#6e0a12",
                "surface-tint": "#4f645b",
                "on-tertiary-fixed-variant": "#536372",
                "on-primary-fixed-variant": "#4b6057",
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
            },
            keyframes: {
                "fade-in": {
                    "0%": { opacity: "0", transform: "translateY(8px)" },
                    "100%": { opacity: "1", transform: "translateY(0)" },
                },
                "slide-in": {
                    "0%": { transform: "translateX(-100%)" },
                    "100%": { transform: "translateX(0)" },
                },
                "scale-in": {
                    "0%": { opacity: "0", transform: "scale(0.95)" },
                    "100%": { opacity: "1", transform: "scale(1)" },
                },
            },
            animation: {
                "fade-in": "fade-in 0.3s ease-out",
                "slide-in": "slide-in 0.3s ease-out",
                "scale-in": "scale-in 0.2s ease-out",
            },
        },
    },
    plugins: [],
}
